Repository python-ldap/python-ldap, pull requests merged in 2020-06, with the labels that each got.

#340 Don't overallocate memory in attrs_from_List()
  Modules/LDAPObject.c
Labels: bug, correctness

#338 Document that TLS options are backend specific
  Doc/reference/ldap.rst
Labels: doc

#262 Store message id for exceptions raised from result4()
  Doc/reference/ldap.rst
  Tests/t_ldapobject.py
Labels: needs-docs, needs-tests

#335 Tox: replace setup.py test with unittest discover
  .coveragerc
  .travis.yml
  tox.ini
Labels: tests

#339 Improve TLS documentation
  Doc/reference/ldap.rst
  Doc/spelling_wordlist.txt
  Lib/ldap/constants.py
  Makefile
  Modules/constants_generated.h
Labels: doc

#342 Fix NULL deref and checks in LDAPmessage_to_python
  Modules/message.c
Labels: correctness

#349 Remove coverage
  .travis.yml
  tox.ini
Labels: tests

#351 Syncrepl fails to parse SyncInfoMessage when the message is a syncIdSet
  Lib/ldap/syncrepl.py
  Tests/t_ldap_syncrepl.py
Labels: bug

#358 Remove Python 2 support
  .travis.yml
  Doc/bytes_mode.rst
  Doc/faq.rst
  Doc/reference/ldap.rst
  Doc/reference/ldapurl.rst
  Doc/sample_workflow.rst
  Lib/ldap/cidict.py
  Lib/ldap/compat.py
  Lib/ldap/controls/sss.py
  Lib/ldap/dn.py
  Lib/ldap/functions.py
  Lib/ldap/ldapobject.py
  Lib/ldap/schema/models.py
  Lib/ldap/schema/subentry.py
  Lib/ldapurl.py
  Lib/ldif.py
  Lib/slapdtest/_slapdtest.py
  Modules/LDAPObject.h
  Modules/ldapmodule.c
  Tests/t_bind.py
  Tests/t_cext.py
  Tests/t_edit.py
  Tests/t_ldap_dn.py
  Tests/t_ldap_syncrepl.py
  Tests/t_ldapobject.py
  Tests/t_ldapurl.py
  Tests/t_ldif.py
  setup.py
  tox.ini
Labels: enhancement

#361 Add words to spellchecker
  Doc/spelling_wordlist.txt
Labels: tests

#362 Force Python 3 tox on Travis CI
  .travis.yml
Labels: tests

#360 Fix macOS SDK builds without ldap_init_fd
  .travis.yml
  Doc/reference/ldap.rst
  Lib/ldap/constants.py
  Lib/ldap/ldapobject.py
  Lib/slapdtest/__init__.py
  Lib/slapdtest/_slapdtest.py
  Modules/common.h
  Modules/constants_generated.h
  Modules/functions.c
  Tests/t_cext.py
  Tests/t_ldapobject.py
  setup.py
  tox.ini
Labels: bug
